force-app/main/default/objects/SubTodo__c/SubTodo__c.object-meta.xml
<CustomObject>
    <label>SubTodo</label>
    <nameField>
        <label>SubTodo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubTodos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SubTodo__c/fields/Master__c.field-meta.xml
<CustomField>
    <fullName>Master__c</fullName>
    <label>Master</label>
    <referenceTo>Todo__c</referenceTo>
    <relationshipLabel>SubTodos</relationshipLabel>
    <relationshipName>SubTodos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Todo__c/Todo__c.object-meta.xml
<CustomObject>
    <label>Todo</label>
    <nameField>
        <label>Todo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Todos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Todo__c/recordTypes/Later.recordType-meta.xml
<RecordType>
    <fullName>Later</fullName>
    <active>true</active>
    <label>Later</label>
</RecordType>

force-app/main/default/classes/SubTodoTriggerHandlerTest.cls
@IsTest
public with sharing class SubTodoTriggerHandlerTest {
    @IsTest
    public static void afterInsertTest() {
        Test.setMock(HttpCalloutMock.class, new TodoCalloutMock());
        Group queue = new Group(Name = 'Later', Type = 'Queue');
        insert queue;
        Id testRecordTypeId = Schema.SObjectType.Todo__c.getRecordTypeInfosByName().get('Later').getRecordTypeId();
        Todo__c todo = TestDataFactory.TODO.createTodo('Test todo', testRecordTypeId, 'In progress');
        Boolean noError = true;
        TodoTriggerHandler.enableTrigger = false;
        insert todo;
        Test.startTest();
        try {
            SubTodo__c subTodo = new SubTodo__c(Master__c = todo.Id);
            insert subTodo;
        } catch (StatusCodeException e) {
            System.debug(e);
            noError = false;
        }
        Test.stopTest();
        System.assertEquals(true, noError, 'Error during SubTodo__c afterInsert process');
    }

    @IsTest
    public static void afterUpdateTest() {
        Test.setMock(HttpCalloutMock.class, new TodoCalloutMock());
        Group queue = new Group(Name = 'Later', Type = 'Queue');
        insert queue;
        Id testRecordTypeId = Schema.SObjectType.Todo__c.getRecordTypeInfosByName().get('Later').getRecordTypeId();
        Todo__c todo = TestDataFactory.TODO.createTodo('Test todo', testRecordTypeId, 'In progress');
        Boolean noError = true;
        TodoTriggerHandler.enableTrigger = false;
        insert todo;
        SubTodoTriggerHandler.enableTrigger = false;
        SubTodo__c subTodo = new SubTodo__c(Master__c = todo.Id);
        insert subTodo;
        SubTodoTriggerHandler.enableTrigger = true;
        Test.startTest();
        try {
            subTodo.Done__c = true;
            update subTodo;
        } catch (StatusCodeException e) {
            System.debug(e);
            noError = false;
        }
        Test.stopTest();
        System.assertEquals(true, noError, 'Error during SubTodo__c afterUpdate process');
    }

    @IsTest
    public static void afterDeleteTest() {
        Test.setMock(HttpCalloutMock.class, new TodoCalloutMock());
        Group queue = new Group(Name = 'Later', Type = 'Queue');
        insert queue;
        Id testRecordTypeId = Schema.SObjectType.Todo__c.getRecordTypeInfosByName().get('Later').getRecordTypeId();
        Todo__c todo = TestDataFactory.TODO.createTodo('Test todo', testRecordTypeId, 'In progress');
        Boolean noError = true;
        TodoTriggerHandler.enableTrigger = false;
        insert todo;
        SubTodoTriggerHandler.enableTrigger = false;
        SubTodo__c subTodo = new SubTodo__c(Master__c = todo.Id);
        insert subTodo;
        SubTodoTriggerHandler.enableTrigger = true;
        Test.startTest();
        try {
            delete subTodo;
        } catch (StatusCodeException e) {
            System.debug(e);
            noError = false;
        }
        Test.stopTest();
        System.assertEquals(true, noError, 'Error during SubTodo__c afterDelete process');
    }

    @IsTest
    public static void afterUndeleteTest() {
        Test.setMock(HttpCalloutMock.class, new TodoCalloutMock());
        Group queue = new Group(Name = 'Later', Type = 'Queue');
        insert queue;
        Id testRecordTypeId = Schema.SObjectType.Todo__c.getRecordTypeInfosByName().get('Later').getRecordTypeId();
        Todo__c todo = TestDataFactory.TODO.createTodo('Test todo', testRecordTypeId, 'In progress');
        Boolean noError = true;
        TodoTriggerHandler.enableTrigger = false;
        insert todo;
        SubTodoTriggerHandler.enableTrigger = false;
        SubTodo__c subTodo = new SubTodo__c(Master__c = todo.Id);
        insert subTodo;
        delete subTodo;
        SubTodoTriggerHandler.enableTrigger = true;
        Test.startTest();
        try {
            undelete subTodo;
        } catch (StatusCodeException e) {
            System.debug(e);
            noError = false;
        }
        Test.stopTest();
        System.assertEquals(true, noError, 'Error during SubTodo__c afterDelete process');
    }
}