force-app/main/default/objects/Todo__c/Todo__c.object-meta.xml
<CustomObject>
    <label>Todo</label>
    <nameField>
        <label>Todo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Todos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Todo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to Take</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Todo__c/recordTypes/Later.recordType-meta.xml
<RecordType>
    <fullName>Later</fullName>
    <active>true</active>
    <label>Later</label>
</RecordType>

force-app/main/default/classes/TodoServiceTest.cls
@IsTest
public with sharing class TodoServiceTest {
    @TestSetup
    public static void init() {
        Id testRecordTypeId = Schema.SObjectType.Todo__c.getRecordTypeInfosByName().get('Later').getRecordTypeId();
        TodoTriggerHandler.enableTrigger = false;
        TestDataFactory.TODO.createTodoList(5, 'Test todo', testRecordTypeId, 'In progress');
    }

    @IsTest
    public static void createTodoTest() {
        List<Todo__c> todosToSend = [
                SELECT ToDo_External_Id__c, Name, Status__c, RecordType.DeveloperName, Description__c
                FROM Todo__c
        ];
        for (Todo__c todo : todosToSend) {
            todo.Id = null;
        }
        RestRequest request = new RestRequest();
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(JSON.serialize(todosToSend));
        RestContext.request = request;
        Test.startTest();
        String todoResult = TodoService.createTodo();
        Test.stopTest();
        List<Todo__c> todoFromResult = (List<Todo__c>) JSON.deserialize(todoResult, List<Todo__c>.class);
        System.assertEquals(false, todoFromResult.isEmpty(), 'Result list is empty after createTodo');
    }

    @IsTest
    public static void updateTodoTest() {
        List<Todo__c> todosToSend = [
                SELECT Id, ToDo_External_Id__c, Name, Status__c, RecordType.DeveloperName, Description__c
                FROM Todo__c
        ];
        for (Todo__c todo : todosToSend) {
            todo.ToDo_External_Id__c = todo.Id;
        }
        TodoTriggerHandler.enableTrigger = false;
        update todosToSend;
        RestRequest request = new RestRequest();
        request.httpMethod = 'PATCH';
        request.requestBody = Blob.valueOf(JSON.serialize(todosToSend));
        RestContext.request = request;
        Test.startTest();
        String todoResult = TodoService.updateTodo();
        Test.stopTest();
        List<Todo__c> todoFromResult = (List<Todo__c>) JSON.deserialize(todoResult, List<Todo__c>.class);
        System.assertEquals(false, todoFromResult.isEmpty(), 'Result list is empty after updateTodo');
    }

    @IsTest
    public static void deleteTodoTest() {
        Map<Id, Todo__c> todosByIdsMap = new Map<Id, Todo__c>([
                SELECT Id, ToDo_External_Id__c, Name, Status__c, RecordType.DeveloperName, Description__c
                FROM Todo__c
        ]);
        for (Todo__c todo : todosByIdsMap.values()) {
            todo.ToDo_External_Id__c = todo.Id;
        }
        TodoTriggerHandler.enableTrigger = false;
        update todosByIdsMap.values();
        RestRequest request = new RestRequest();
        request.httpMethod = 'DELETE';
        request.requestBody = Blob.valueOf(JSON.serialize(todosByIdsMap.keySet()));
        RestContext.request = request;
        Test.startTest();
        String todoResult = TodoService.deleteTodo();
        Test.stopTest();
        List<Todo__c> todoFromResult = (List<Todo__c>) JSON.deserialize(todoResult, List<Todo__c>.class);
        System.assertEquals(false, todoFromResult.isEmpty(), 'Result list is empty after deleteTodo');
    }

    @IsTest
    public static void undeleteTodoTest() {
        Map<Id, Todo__c> todosByIdsMap = new Map<Id, Todo__c>([
                SELECT Id, ToDo_External_Id__c, Name, Status__c, RecordType.DeveloperName, Description__c
                FROM Todo__c
        ]);
        for (Todo__c todo : todosByIdsMap.values()) {
            todo.ToDo_External_Id__c = todo.Id;
        }
        TodoTriggerHandler.enableTrigger = false;
        update todosByIdsMap.values();
        delete todosByIdsMap.values();
        RestRequest request = new RestRequest();
        request.httpMethod = 'PUT';
        request.requestBody = Blob.valueOf(JSON.serialize(todosByIdsMap.keySet()));
        RestContext.request = request;
        Test.startTest();
        String todoResult = TodoService.undeleteTodo();
        Test.stopTest();
        List<Todo__c> todoFromResult = (List<Todo__c>) JSON.deserialize(todoResult, List<Todo__c>.class);
        System.assertEquals(false, todoFromResult.isEmpty(), 'Result list is empty after undeleteTodo');
    }
}