force-app/main/default/objects/Todo__c/Todo__c.object-meta.xml
<CustomObject>
    <label>Todo</label>
    <nameField>
        <label>Todo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Todos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Todo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to Take</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Todo__c/recordTypes/Today.recordType-meta.xml
<RecordType>
    <fullName>Today</fullName>
    <active>true</active>
    <label>Today</label>
</RecordType>

force-app/main/default/objects/ToDo_Batch_Setting__mdt/ToDo_Batch_Setting__mdt.object-meta.xml
<CustomObject>
    <label>ToDo Batch Setting</label>
    <pluralLabel>ToDo Batch Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ToDo_Batch_Setting__mdt/fields/Number_of_Days_to_Delete__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Days_to_Delete__c</fullName>
    <label>Number of Days to Delete</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ToDoCleanerBatchTest.cls
@IsTest
public with sharing class ToDoCleanerBatchTest {

    @IsTest
    static void testBatchSchedule() {
        Test.startTest();
        ToDoCleanerBatch todoCleanerBatch = new ToDoCleanerBatch();
        String cron = '0 0 * * * ?';
        String jobId = System.schedule('ToDo__c cleaner job every hour', cron, todoCleanerBatch);
        CronTrigger cronTrigger = [SELECT Id, CronExpression, TimesTriggered FROM CronTrigger WHERE Id = :jobId];
        Test.stopTest();
        System.assertEquals(0, cronTrigger.TimesTriggered);
        System.assertEquals(cron, cronTrigger.CronExpression);
    }

    @IsTest
    static void testBatchIterable() {
        Todo__c todo = new Todo__c(
                Name = 'Test todo',
                Status__c = 'In progress'
        );
        TodoTriggerHandler.enableTrigger = false;
        insert todo;
        List<ToDo_Batch_Setting__mdt> toDoBatchSettings = [
                SELECT Id, DeveloperName, Number_of_Days_to_Delete__c
                FROM ToDo_Batch_Setting__mdt
                WHERE DeveloperName = 'Todo_Batch'
                LIMIT 1
        ];
        Date dateToClean = Date.today().addDays(-Integer.valueOf(toDoBatchSettings.get(0).Number_of_Days_to_Delete__c + 1));
        Test.setCreatedDate(todo.Id, dateToClean);
        Test.startTest();
        Database.executeBatch(new ToDoCleanerBatch());
        Test.stopTest();
        List<Todo__c> todos = [SELECT Id FROM Todo__c WHERE Id = :todo.Id];
        System.assertEquals(true, todos.isEmpty());
    }

}