force-app/main/default/objects/Todo__c/Todo__c.object-meta.xml
<CustomObject>
    <label>Todo</label>
    <nameField>
        <label>Todo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Todos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Todo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to Take</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
public with sharing class TestDataFactory {
    
    //public static TestRecordTypeFactory RECORDTYPE = new TestRecordTypeFactory();
    public static TestTodoFactory TODO = new TestTodoFactory();
    public static TestQueueFactory QUEUE = new TestQueueFactory();
	
    public class TestTodoFactory{
        public Todo__c createTodo(String name, Id recordTypeId, String status) {
            return new Todo__c(Name = name, RecordTypeId = recordTypeId, Status__c = status);
        }

        public List<Todo__c> createTodoList(Integer count, String Name, Id recordTypeId, String status) {
            List<Todo__c> todos = new List<Todo__c>();
            for(Integer i = 0; i < count; i++) {
                todos.add(createTodo(name, recordTypeId, status));
            }
            insert todos;
            return todos;
        }
    }

    public class TestQueueFactory{
        public Group createQueue(String name, String type) {
            Group queue = new Group(Name = name, Type = type);
            insert queue;
            return queue;
        }
    }
}