force-app/main/default/objects/Todo__c/Todo__c.object-meta.xml
<CustomObject>
    <label>Todo</label>
    <nameField>
        <label>Todo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Todos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Todo__c/recordTypes/Today.recordType-meta.xml
<RecordType>
    <fullName>Today</fullName>
    <active>true</active>
    <label>Today</label>
</RecordType>

force-app/main/default/objects/ToDo_Batch_Setting__mdt/ToDo_Batch_Setting__mdt.object-meta.xml
<CustomObject>
    <label>ToDo Batch Setting</label>
    <pluralLabel>ToDo Batch Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ToDo_Batch_Setting__mdt/fields/Number_of_Days_to_Delete__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Days_to_Delete__c</fullName>
    <label>Number of Days to Delete</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ToDoCleanerBatch.cls
public with sharing class ToDoCleanerBatch implements Database.Batchable<SObject>, Schedulable {

    public Iterable<SObject> start(Database.BatchableContext BC) {
        List<ToDo_Batch_Setting__mdt> toDoBatchSettings = [
                SELECT Id, DeveloperName, Number_of_Days_to_Delete__c
                FROM ToDo_Batch_Setting__mdt
                WHERE DeveloperName = 'Todo_Batch'
                LIMIT 1
        ];
        Date dateToClean = Date.today().addDays(-Integer.valueOf(toDoBatchSettings.get(0).Number_of_Days_to_Delete__c));
        return Database.getQueryLocator([
                SELECT Id, CreatedDate
                FROM Todo__c
                WHERE CreatedDate < :dateToClean
        ]);
    }

    public void execute(SchedulableContext schedulableContext) {
        Database.executeBatch(this);
    }

    public void execute(Database.BatchableContext BC, List<SObject> todosList) {
        List<Todo__c> todos = todosList;
        if (!todos.isEmpty()) {
            System.debug('Number of Todo__c records to delete: ' + todos.size());
            delete todos;
        }
    }

    public void finish(Database.BatchableContext param1) {
    }

}